# FIELD CONSTANTS
MAX_CREDENTIAL_LEN = 120

# LISTING STATUS CONSTANTS
DEFAULT_LISTING_STATUS = 'inactive'
INACTIVE = 'inactive'
ACTIVE = 'active'
PENDING = 'pending'
LISTING_STATUSES = [INACTIVE, ACTIVE, PENDING]

# CODE STATUSES:
OK = 200
CREATED = 201
UPDATED = 202
DELETED = 204
BAD_REQUEST = 400
FORBIDDEN = 403
NOT_FOUND = 404
SERVER_ERROR = 500
