"""empty message

Revision ID: e77b7531251d
Revises: 
Create Date: 2021-10-05 13:23:55.777471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77b7531251d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=True),
    sa.Column('client_info', sa.Text(), nullable=True),
    sa.Column('num_listings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('pos_responsibility', sa.Text(), nullable=True),
    sa.Column('min_qualifications', sa.Text(), nullable=True),
    sa.Column('pref_qualifications', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
