"""empty message

Revision ID: eed4e824cbe4
Revises: 
Create Date: 2021-10-02 20:41:21.747460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed4e824cbe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=True),
    sa.Column('company_info', sa.Text(), nullable=True),
    sa.Column('num_listings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('pos_responsibility', sa.Text(), nullable=True),
    sa.Column('min_qualifictions', sa.Text(), nullable=True),
    sa.Column('pref_qualifictions', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=True)
    )
    op.drop_table('listings')
    op.drop_table('companies')
    # ### end Alembic commands ###
