# FIELD CONSTANTS
MAX_CREDENTIAL_LEN = 120

# LISTING STATUS CONSTANTS
DEFAULT_LISTING_STATUS = 'inactive'
INACTIVE = 'inactive'
ACTIVE = 'active'
PENDING = 'pending'
REJECTED = 'rejected'
LISTING_STATUSES = [INACTIVE, ACTIVE, PENDING, REJECTED]
